language: python

jobs:
  include:
    - os: osx
      python: "3.8"
      osx_image: xcode12.2
    - os: linux
      python: "3.6"
      dist: xenial
    - os: linux
      python: "3.7"
      dist: xenial

cache: pip

# command to install dependencies
install:
  - pip install .                       # for AegeanTools
  - pip install coveralls               # for coverage
  - pip install codacy-coverage         # for code quality
  - pip install -r doc/requirements.txt # for sphinx documentation 
# command to run tests
script:
  - coverage run setup.py test          # run tests
  - coverage combine                    # combine test results
  - make -C doc html                    # Build documentation
after_success:
  - coveralls
  - python-codacy-coverage -r coverage.xml
